[package]
name = "ddrescue_error_mapping"
license = "AGPL-3.0-or-later"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]